apiVersion: apps/v1
kind: Deployment
metadata:
  name: ephemeral-containers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ephemeral-containers
  template:
    metadata:
      labels:
        app: ephemeral-containers
    spec:
      containers:
        - name: ephemeral-containers
          image: ephemeral-containers
          imagePullPolicy: Never
          ports:
            - name: app-port
              containerPort: 5000
          readinessProbe:
            httpGet:
              path: /healthz
              port: app-port
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ephemeral-containers-service
spec:
  selector:
    app: ephemeral-containers
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
