apiVersion: apps/v1
kind: Deployment
metadata:
  name: hp-busybox-deployment
spec:
  selector:
    matchLabels:
      app: hp-busybox
  replicas: 1
  template:
    metadata:
      labels:
        app: hp-busybox
    spec:
      containers:
      - name: hp-busybox
        image: busybox:1.36
        command:
          - sleep
          - "3600"
        resources:
          limits:
            cpu: 1000m
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 4Gi
