apiVersion: apps/v1
kind: Deployment
metadata:
  name: comprehensive-readiness-probe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comprehensive-readiness-probe
  template:
    metadata:
      labels:
        app: comprehensive-readiness-probe
    spec:
      containers:
        - name: comprehensive-readiness-probe
          image: comprehensive-readiness-probe
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: mongodb://mongodb-service:27017/myapp
            - name: CACHE_URL
              value: redis://redis-service:6379
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4
          ports:
            - containerPort: 27017

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: comprehensive-readiness-probe-service
spec:
  selector:
    app: comprehensive-readiness-probe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
