apiVersion: batch/v1
kind: Job
metadata:
  name: busybox-job
  labels:
   app: busybox-job
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox:1.36.1
        command: ["/bin/sh", "-c", "echo Hello Kubernetes! && exit 0"]
      restartPolicy: OnFailure
